// Code generated by mockery v2.53.3. DO NOT EDIT.

package command_mocks

import (
	context "context"

	user "github.com/rubemlrm/go-api-bootstrap/internal/user/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateUserHandler is an autogenerated mock type for the CreateUserHandler type
type MockCreateUserHandler struct {
	mock.Mock
}

type MockCreateUserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateUserHandler) EXPECT() *MockCreateUserHandler_Expecter {
	return &MockCreateUserHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, cmd
func (_m *MockCreateUserHandler) Handle(ctx context.Context, cmd *user.UserCreate) (user.ID, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 user.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserCreate) (user.ID, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserCreate) user.ID); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(user.ID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.UserCreate) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateUserHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockCreateUserHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *user.UserCreate
func (_e *MockCreateUserHandler_Expecter) Handle(ctx interface{}, cmd interface{}) *MockCreateUserHandler_Handle_Call {
	return &MockCreateUserHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, cmd)}
}

func (_c *MockCreateUserHandler_Handle_Call) Run(run func(ctx context.Context, cmd *user.UserCreate)) *MockCreateUserHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.UserCreate))
	})
	return _c
}

func (_c *MockCreateUserHandler_Handle_Call) Return(_a0 user.ID, _a1 error) *MockCreateUserHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateUserHandler_Handle_Call) RunAndReturn(run func(context.Context, *user.UserCreate) (user.ID, error)) *MockCreateUserHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateUserHandler creates a new instance of MockCreateUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateUserHandler {
	mock := &MockCreateUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
