structname: 'Mock{{.InterfaceName}}'
pkgname: mocks
filename: "mock_{{.InterfaceName}}.go"
template: testify
dir: '{{.InterfaceDir}}/mocks'
packages:
  github.com/rubemlrm/go-api-bootstrap/internal/common/decorator:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/common/logger:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/common/validations:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/user:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/user/app/command:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/user/app/query:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/user/domain/user:
    config:
      all: true
  github.com/rubemlrm/go-api-bootstrap/internal/user/ports:
    config:
      all: true
