---
version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
