name: go-api-hexa-sandbox

networks:
  go-api-hexa-sandbox:

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - go-api-hexa-sandbox
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - go-api-hexa-sandbox
    ports:
      - 6379:6379
  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    restart: always
    ports:
      - 5775:5775/udp
      - 6832:6832/udp
      - 5778:5778
      - 6831:6831
      - 16686:16686
      - 4317:4317
      - 14268:14268
    networks:
      - go-api-hexa-sandbox
