POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "teste"
}

###
GET http://localhost:8080/api/v1/users/1
Accept: application/json

###
###
GET http://localhost:8080/api/v1/users
Accept: application/json

###