// Code generated by mockery v2.53.3. DO NOT EDIT.

package user_mocks

import (
	context "context"

	user "github.com/rubemlrm/go-api-bootstrap/internal/user/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockUserWriter is an autogenerated mock type for the UserWriter type
type MockUserWriter struct {
	mock.Mock
}

type MockUserWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserWriter) EXPECT() *MockUserWriter_Expecter {
	return &MockUserWriter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, u
func (_m *MockUserWriter) Create(ctx context.Context, u *user.UserCreate) (user.ID, error) {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 user.ID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserCreate) (user.ID, error)); ok {
		return rf(ctx, u)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserCreate) user.ID); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Get(0).(user.ID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.UserCreate) error); ok {
		r1 = rf(ctx, u)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.UserCreate
func (_e *MockUserWriter_Expecter) Create(ctx interface{}, u interface{}) *MockUserWriter_Create_Call {
	return &MockUserWriter_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockUserWriter_Create_Call) Run(run func(ctx context.Context, u *user.UserCreate)) *MockUserWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.UserCreate))
	})
	return _c
}

func (_c *MockUserWriter_Create_Call) Return(_a0 user.ID, _a1 error) *MockUserWriter_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserWriter_Create_Call) RunAndReturn(run func(context.Context, *user.UserCreate) (user.ID, error)) *MockUserWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserWriter creates a new instance of MockUserWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserWriter {
	mock := &MockUserWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
