// Code generated by mockery v2.53.3. DO NOT EDIT.

package user_mocks

import (
	context "context"

	user "github.com/rubemlrm/go-api-bootstrap/internal/user/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx
func (_m *MockReader) All(ctx context.Context) (*[]user.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 *[]user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]user.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]user.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockReader_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) All(ctx interface{}) *MockReader_All_Call {
	return &MockReader_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockReader_All_Call) Run(run func(ctx context.Context)) *MockReader_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReader_All_Call) Return(_a0 *[]user.User, _a1 error) *MockReader_All_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_All_Call) RunAndReturn(run func(context.Context) (*[]user.User, error)) *MockReader_All_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockReader) Get(ctx context.Context, id user.ID) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.ID) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockReader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id user.ID
func (_e *MockReader_Expecter) Get(ctx interface{}, id interface{}) *MockReader_Get_Call {
	return &MockReader_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockReader_Get_Call) Run(run func(ctx context.Context, id user.ID)) *MockReader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ID))
	})
	return _c
}

func (_c *MockReader_Get_Call) Return(_a0 *user.User, _a1 error) *MockReader_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_Get_Call) RunAndReturn(run func(context.Context, user.ID) (*user.User, error)) *MockReader_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
