// Code generated by mockery v2.31.0. DO NOT EDIT.

package validations_mocks

import mock "github.com/stretchr/testify/mock"

// MockValidater is an autogenerated mock type for the Validater type
type MockValidater struct {
	mock.Mock
}

type MockValidater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidater) EXPECT() *MockValidater_Expecter {
	return &MockValidater_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: val
func (_m *MockValidater) Check(val interface{}) bool {
	ret := _m.Called(val)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}) bool); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValidater_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockValidater_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - val interface{}
func (_e *MockValidater_Expecter) Check(val interface{}) *MockValidater_Check_Call {
	return &MockValidater_Check_Call{Call: _e.mock.On("Check", val)}
}

func (_c *MockValidater_Check_Call) Run(run func(val interface{})) *MockValidater_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidater_Check_Call) Return(_a0 bool) *MockValidater_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidater_Check_Call) RunAndReturn(run func(interface{}) bool) *MockValidater_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CheckWithTranslations provides a mock function with given fields: val
func (_m *MockValidater) CheckWithTranslations(val interface{}) error {
	ret := _m.Called(val)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidater_CheckWithTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckWithTranslations'
type MockValidater_CheckWithTranslations_Call struct {
	*mock.Call
}

// CheckWithTranslations is a helper method to define mock.On call
//   - val interface{}
func (_e *MockValidater_Expecter) CheckWithTranslations(val interface{}) *MockValidater_CheckWithTranslations_Call {
	return &MockValidater_CheckWithTranslations_Call{Call: _e.mock.On("CheckWithTranslations", val)}
}

func (_c *MockValidater_CheckWithTranslations_Call) Run(run func(val interface{})) *MockValidater_CheckWithTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidater_CheckWithTranslations_Call) Return(_a0 error) *MockValidater_CheckWithTranslations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidater_CheckWithTranslations_Call) RunAndReturn(run func(interface{}) error) *MockValidater_CheckWithTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidater creates a new instance of MockValidater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidater {
	mock := &MockValidater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
