// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// User defines model for User.
type User struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// UserWithID defines model for UserWithID.
type UserWithID struct {
	Email    string `json:"email"`
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = User
