// Code generated by mockery v2.53.3. DO NOT EDIT.

package query_mocks

import (
	context "context"

	query "github.com/rubemlrm/go-api-bootstrap/internal/user/app/query"
	mock "github.com/stretchr/testify/mock"

	user "github.com/rubemlrm/go-api-bootstrap/internal/user/domain/user"
)

// MockGetUserHandler is an autogenerated mock type for the GetUserHandler type
type MockGetUserHandler struct {
	mock.Mock
}

type MockGetUserHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetUserHandler) EXPECT() *MockGetUserHandler_Expecter {
	return &MockGetUserHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, q
func (_m *MockGetUserHandler) Handle(ctx context.Context, q query.UserSearch) (*user.User, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.UserSearch) (*user.User, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.UserSearch) *user.User); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.UserSearch) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetUserHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockGetUserHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - q query.UserSearch
func (_e *MockGetUserHandler_Expecter) Handle(ctx interface{}, q interface{}) *MockGetUserHandler_Handle_Call {
	return &MockGetUserHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, q)}
}

func (_c *MockGetUserHandler_Handle_Call) Run(run func(ctx context.Context, q query.UserSearch)) *MockGetUserHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.UserSearch))
	})
	return _c
}

func (_c *MockGetUserHandler_Handle_Call) Return(_a0 *user.User, _a1 error) *MockGetUserHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetUserHandler_Handle_Call) RunAndReturn(run func(context.Context, query.UserSearch) (*user.User, error)) *MockGetUserHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetUserHandler creates a new instance of MockGetUserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetUserHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetUserHandler {
	mock := &MockGetUserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
