// Code generated by mockery v2.53.3. DO NOT EDIT.

package validations_mocks

import (
	validations "github.com/rubemlrm/go-api-bootstrap/internal/common/validations"
	mock "github.com/stretchr/testify/mock"
)

// MockValidationFunc is an autogenerated mock type for the ValidationFunc type
type MockValidationFunc struct {
	mock.Mock
}

type MockValidationFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidationFunc) EXPECT() *MockValidationFunc_Expecter {
	return &MockValidationFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockValidationFunc) Execute(_a0 string, _a1 ...validations.Option) (*validations.Validator, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *validations.Validator
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...validations.Option) (*validations.Validator, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(string, ...validations.Option) *validations.Validator); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validations.Validator)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...validations.Option) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockValidationFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockValidationFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 string
//   - _a1 ...validations.Option
func (_e *MockValidationFunc_Expecter) Execute(_a0 interface{}, _a1 ...interface{}) *MockValidationFunc_Execute_Call {
	return &MockValidationFunc_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockValidationFunc_Execute_Call) Run(run func(_a0 string, _a1 ...validations.Option)) *MockValidationFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]validations.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(validations.Option)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockValidationFunc_Execute_Call) Return(_a0 *validations.Validator, _a1 error) *MockValidationFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockValidationFunc_Execute_Call) RunAndReturn(run func(string, ...validations.Option) (*validations.Validator, error)) *MockValidationFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidationFunc creates a new instance of MockValidationFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidationFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidationFunc {
	mock := &MockValidationFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
